### ISSUE TITLE
annoying(very): `Did you mean "repository"?`

### ISSUE THREAD

**Issue by Agent-E11** [elijah-potter/harper#106]
Whenever I type "repo", harper-ls tries suggesting I replace it with "repository". I understand that this is intended, and it would be useful if I did want to use "repository" instead of "repo", but I _don't_ want to use "repository", and there is no way to tell harper-ls that.

**Comment by elijah-potter** [comment]
I agree that they should both be considered valid. I'm creating a release now with the change.

**Comment by elijah-potter** [comment]
Alright! The release is published. It should be available via Mason soon. Give it a whirl and close this issue once it's confirmed to be fixed. Thanks for speaking up!

**Comment by Agent-E11** [comment]
Thanks! Although, I do think there is a deeper problem than the difference between "repo" and "repository". I think it shouldn't even suggest the "Did you mean X?" if the word is in the dictionary.

(Unfortunately, Mason hasn't updated yet, so I probably won't be able to test it today)

**Comment by Agent-E11** [comment]
I have tested it, and it no longer flags "repo".

I will close this issue, but I think you should consider my suggestion above.
