### ISSUE TITLE
How does it work? FAQs request

### ISSUE THREAD

**Issue by brianangulo** [elijah-potter/harper#110]
Hey really cool project thank you for your contributions to open source! My question is a direct one: on a high level, how does harper work? Instead of making my assumptions based on the code I'd love to read straight from the source if able, thank you. PS: once you get enough of these types of questions you may be able to put an FAQ section together.

**Comment by tom-avilius** [comment]
You should go through this one, it does give some insight:
https://github.com/elijah-potter/harper/blob/master/harper-ls/README.md

Further, this reddit post is somewhat close to a FAQ section. He has answered a lot of questions there.
https://www.reddit.com/r/neovim/comments/1elhsxb/been_writing_a_better_grammar_checker_for_neovim/

But yes, an official FAQ section could be put up when the project reaches a certain stage.

**Comment by LandonSchropp** [comment]
@elijah-potter Thanks for creating this repo!

After reading the architecture doc, my main question is: what's the long-term plan for Harper? Will it always stick to patterns, or are you planning on expanding from there? Will it eventually be expanded to include the full capabilities of checkers like Grammarly or LanguageTool?

**Comment by brianangulo** [comment]
> Sorry it took so long for me to get to this. I've created a draft of an [architecture document](https://github.com/elijah-potter/harper/blob/master/ARCHITECTURE.md). Give it a read and let me know if you have any questions it _doesn't_ answer.

Thank you @elijah-potter I think this along with the linked docs in there helps a ton. Closing this issue since my question is answered but I'm curious about LandonSchropp's question as well. Thanks.
