### ISSUE TITLE
Feat: Add harper-ls to Zed

### ISSUE THREAD

**Issue by MahanRahmati** [elijah-potter/harper#114]
Hello there!
Thank you for creating this nice checker!
Can you add it to [Zed](https://github.com/zed-industries/zed/)?
You can check the documentation of Zed for creating extensions [here](https://zed.dev/docs/extensions/languages#language-servers).

**Comment by Stef16Robbe** [comment]
Hi, I'm working on this. (non-functional) code can be found here: https://github.com/Stef16Robbe/harper_zed

Still need some help with configuring the extension so I opened a discussion for anyone interested: https://github.com/zed-industries/zed/discussions/17344

**Comment by Stef16Robbe** [comment]
That makes... a lot more sense 😅. Thanks for mentioning! In that case I know how to continue ^^.

**Comment by Stef16Robbe** [comment]
So 0.0.1 is working when harper-lsp is preinstalled, working making sure that the extension will do that as a backup when needed.

**Comment by elijah-potter** [comment]
That's fantastic news! Keep us updated as to when you've got everything working.

**Comment by Stef16Robbe** [comment]
FYI @MahanRahmati Harper extension is now available for installation: https://github.com/zed-industries/extensions/pull/1404

**Comment by elijah-potter** [comment]
@Stef16Robbe I'm not super familiar with Zed. Would you mind writing out some installation instructions (or maybe just a link) I could include on the website and in other documentation?

**Comment by Stef16Robbe** [comment]
@elijah-potter Thanks to @lukasmwerner https://github.com/Stef16Robbe/harper_zed/pull/1 it's there now 😊

**Comment by elijah-potter** [comment]
Love it! I'll add links to the plugin. I think this issue is done then.
