### ISSUE TITLE
[ Question ] Is it possible to stop the server if too many errors are found?

### ISSUE THREAD

**Issue by OXY2DEV** [elijah-potter/harper#119]
## Problem

When opening `CHANGELOG.md` files `harper-ls` can cause everything else to halt(most likely caused by Neovim waiting for the response from the LSP).

Is it possible for the server to stop sending more responses if there are too many errors detected?

> Or is it possible to only send part of the buffer text(current context can be retrieved from `tree-sitter`, as it should be much faster) to the LSP instead of sending the entire buffers text?

**Comment by OXY2DEV** [comment]
Any significantly  large`CHANGELOG.md` file should be enough.

In my case, `noice.nvim`'s [CHANGELOG.md](https://github.com/folke/noice.nvim/blob/main/CHANGELOG.md) file would cause it to get slow.

But you could also test it with other popular plugin's CHANGELOG files too.

**Comment by elijah-potter** [comment]
I looked into this and it seemed to be a pretty significant performance issue (some caches were getting busted WAY too often). I've made some changes that are in the `v0.10.0` release. Once Mason has picked up the changed, would you give it spin?

**Comment by OXY2DEV** [comment]
![Screenshot_2024-08-31-23-53-56-167_com termux-edit](https://github.com/user-attachments/assets/e74e7674-f0c0-4abc-9a0b-a65dc6b8a288)
<sub>Diagnostics not being removed even though they are disabled on insert mode.</sub>

It looks like performance has *improved* by quite a bit. However, it still not bullet-proof yet, as diagnostics seems to struggle a bit(but that could be a hardware limitation).

I would have preferred if it was possible to only send *part* of the buffer(specifically 200 lines around the cursor) to make LSPs faster but I guess that's not a solution.

Anyway, thanks for fixing the issue! I will close the issue.

---

On a side note, is it possible to add my own dictionary to the LSP?

For example, `@param` commonly used in luaCATS annotations is picked up by this LSP leading to a lot of "misspelling" being shown on the screen on large files.

**Comment by elijah-potter** [comment]
> On a side note, is it possible to add my own dictionary to the LSP?

There should be a code action on spelling errors to add to a personal dictionary. Let me know if that's not working for you.

> For example, @param commonly used in luaCATS annotations is picked up by this LSP leading to a lot of "misspelling" being shown on the screen on large files.

This is a larger issue. Harper should ignore these by default. Would you mind opening a new issue with a couple examples of this?

**Comment by OXY2DEV** [comment]
> There should be a code action on spelling errors to add to a personal dictionary. Let me know if that's not working for you.

I am quite new to programming so I wasn't aware of Code actions.

Yes, it works.

> Would you mind opening a new issue with a couple examples of this?

I have opened a new issue about this.
