### ISSUE TITLE
Obsidian 1.7.1 - Won't install

### ISSUE THREAD

**Issue by ms3056** [elijah-potter/harper#121]
Hi - I am on the insider's release and I cannot get the plugin to install. I am also on the windows platform if that matters. 

Here is what I see in the console when I attempt to install the plugin within Obsidian:

```cmd
Error: Request failed, status 404
    at new t (app.js:1:2058736)
    at EK (app.js:1:2058928)
    at app.js:1:2059607
    at app.js:1:237162
    at Object.next (app.js:1:237267)
    at a (app.js:1:235985)
    ```

**Comment by elijah-potter** [comment]
Thanks for bringing this up. I'll give it a run on the insider's release and see what's gone wrong.

**Comment by elijah-potter** [comment]
Upon further inspection, it seems I need to have a specific license of Obsidian to access the insider builds. Does that sound correct?

**Comment by ms3056** [comment]
Yes - you need a Catalyst license:

https://help.obsidian.md/Licenses+and+payment/Catalyst+license

Mike

**Comment by ms3056** [comment]
0.9.5 is installing. Thanks!
