### ISSUE TITLE
Wrong replacement

### ISSUE THREAD

**Issue by ms3056** [elijah-potter/harper#122]
I am getting the correct popup but the wrong replacement

![image](https://github.com/user-attachments/assets/fb0a493b-9ba1-4524-b3d4-483561bb0da4)

It highlights the wrong part of the text and changes the wrong part. 

I use the Default theme, and I turned off all other CSS snippets after this screenshot just to be sure - and sure enough, the error persists.

**Comment by elijah-potter** [comment]
Would it be possible to get a copy of your full document so I can better diagnose the issue?
Thanks for bringing this to my attention!

**Comment by ms3056** [comment]
Well! I tried the plugin today and it it worked perfectly. Perhaps I need to shut  Obsidian down first before testing. Sorry! Works fine today.

**Comment by elijah-potter** [comment]
I'm glad it's working. If it crops up again don't be afraid to reopen the ticket
