### ISSUE TITLE
Installation instructions for Docker

### ISSUE THREAD

**Issue by Shagon94** [elijah-potter/harper#144]
I wanted to try out the project, however even though I see the Dockerifle there are no instructions on how to use it. 

Would it be possible to have a documentation page/wiki explaining with the different installation methods?

Additionally, is there support coming for different languages in the future? Most of the time I write in 3 different languages, but at the moment only American English is supported at the moment.

**Comment by elijah-potter** [comment]
> I wanted to try out the project, however even though I see the Dockerifle there are no instructions on how to use it.

I should add a little documentation on why that's there. That `Dockerfile` is for Harper's [website](https://writewithharper.com), not for Harper itself.

> Would it be possible to have a documentation page/wiki explaining with the different installation methods?

Absolutely. I'll give an update here once its ready. Where are you trying to use Harper? So I can address your use-case directly.


I wanted to try out the project, however even though I see the Dockerifle there are no instructions on how to use it.

Would it be possible to have a documentation page/wiki explaining with the different installation methods?

> Additionally, is there support coming for different languages in the future? Most of the time I write in 3 different languages, but at the moment only American English is supported at the moment.

Yes*. I have plans to support other variants of English (British, for example). Was there a non-english language you were interested in?

**Comment by Shagon94** [comment]
Any language should be an option by providing a language/dict file, not sure what the standard is. I'm somewhat fortunate to be multilingual, however the downside is that sometimes I might mix languages when writing.

> Where are you trying to use Harper? So I can address your use-case directly.

I mostly want a replacement for language tool, as the tool itself makes my CPU hurt. I mostly use it in vscode/markdown editors when editing code or documentation.

**Comment by elijah-potter** [comment]
> Any language should be an option by providing a language/dict file, not sure what the standard is. I'm somewhat fortunate to be multilingual, however the downside is that sometimes I might mix languages when writing.

There isn't a standard for this, since every tool works at least a little differently. 

We're getting a little off topic on this issue, so please refer to one of the other issues that discusses multilingual support. I'll get to it, but right now am swamped with work, so it's unlikely to happen soon.
