### ISSUE TITLE
`harper-ls` process doesn't exit event though neovim quits

### ISSUE THREAD

**Issue by Jaehaks** [elijah-potter/harper#148]
Thank you for your efforts, 

sometimes, even though neovim is closed, harper-ls.exe process doesn't quit itself like this
![image](https://github.com/user-attachments/assets/4b722b5a-e6a4-4f20-b22f-6acf4c21fe7a)

**Comment by Jaehaks** [comment]
I think it is not harper-ls issue, some wrong closing file makes the prolblem as I think

**Comment by wiserfz** [comment]
Is this issue fixed? I have same problem the harper-ls is not quit when the `neovim` is already quit.

<img width="745" height="106" alt="Image" src="https://github.com/user-attachments/assets/05e6f9e7-5cb4-482a-b87c-7d5c1ac4a575" />


This is my harper-ls lspconfig:

```lua
{
    on_attach = function(client, bufnr)
      if vim.fs.dirname(vim.fn.getcwd()) == os.getenv("HOME") .. "/Workspace" then
        vim.lsp.stop_client(client.id)
        return
      end
      M.on_attach(client, bufnr)
    end,
    reuse_client = function(client, config)
      -- reuse client if the name and root_dir matches
      return client.name == config.name and client.config.root_dir == config.root_dir
    end,
    settings = {
      ["harper-ls"] = {
        userDictPath = vim.fn.getcwd() .. "/.harper_dict.txt",
        fileDictPath = vim.fn.getcwd() .. "/.harper_dictionaries",
        diagnosticSeverity = "hint", -- Can also be "information", "warning", or "error"
        markdown = {
          IgnoreLinkTitle = true,
        },
        linters = {
          SpellCheck = true,
          SentenceCapitalization = false,
        },
      },
    },
}
```

@elijah-potter

**Comment by wiserfz** [comment]
> Is this issue fixed? I have same problem the harper-ls is not quit when the `neovim` is already quit.
> 
> <img alt="Image" width="745" height="106" src="https://private-user-images.githubusercontent.com/38970394/523635976-05e6f9e7-5cb4-482a-b87c-7d5c1ac4a575.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUxODAxMDgsIm5iZiI6MTc2NTE3OTgwOCwicGF0aCI6Ii8zODk3MDM5NC81MjM2MzU5NzYtMDVlNmY5ZTctNWNiNC00ODJhLWI4N2MtN2Q1YzFhYzRhNTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA4VDA3NDMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjIwMDhhNzhlNjI5YWI5NTBhNWViMzI5YzFhMWVjNWI2YzMwZTZjZTYxOGMxMDliMzk3NTMxMThiNmZhZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N8B2fhMxkw4V8RqSQaYgmLNEa5HjE6XWRUKDKmOp7e8">
> This is my harper-ls lspconfig:
> 
> {
>     on_attach = function(client, bufnr)
>       if vim.fs.dirname(vim.fn.getcwd()) == os.getenv("HOME") .. "/Workspace" then
>         vim.lsp.stop_client(client.id)
>         return
>       end
>       M.on_attach(client, bufnr)
>     end,
>     reuse_client = function(client, config)
>       -- reuse client if the name and root_dir matches
>       return client.name == config.name and client.config.root_dir == config.root_dir
>     end,
>     settings = {
>       ["harper-ls"] = {
>         userDictPath = vim.fn.getcwd() .. "/.harper_dict.txt",
>         fileDictPath = vim.fn.getcwd() .. "/.harper_dictionaries",
>         diagnosticSeverity = "hint", -- Can also be "information", "warning", or "error"
>         markdown = {
>           IgnoreLinkTitle = true,
>         },
>         linters = {
>           SpellCheck = true,
>           SentenceCapitalization = false,
>         },
>       },
>     },
> }
> [@elijah-potter](https://github.com/elijah-potter)

Sry, I fixed it by update my lspconfig.

```lua
  harper_ls = { -- Grammar Checker
    settings = {
      ["harper-ls"] = {
        userDictPath = vim.fn.getcwd() .. "/.harper_dict.txt",
        fileDictPath = vim.fn.getcwd() .. "/.harper_dictionaries",
        diagnosticSeverity = "hint", -- Can also be "information", "warning", or "error"
        markdown = {
          IgnoreLinkTitle = true,
        },
        linters = {
          SpellCheck = true,
          SentenceCapitalization = false,
        },
      },
    },
  },
```
