### ISSUE TITLE
Feature: allow 'misspellings' that are identifiers

### ISSUE THREAD

**Issue by dvdsk** [elijah-potter/harper#160]
Context: 

I have a doc comment naming an identifier (in this case an parameter of the function). It has an underscore and harper highlights that as a spelling mistake.

Benefits:
- no erroneous warnings
- keeps the docs in sync with the underlying code. Change the name of the parameter of the function and you get a warning :tada:.

Details:
Should probably not allow all identifiers (maybe a config option), function names and parameter names might be a good default.

related: https://github.com/elijah-potter/harper/issues/29

**Comment by elijah-potter** [comment]
This is actually already implemented for identifiers that aren't either snake_case or chain-case. I'll look into getting this done sometime early next week. Sorry for the delay!

**Comment by elijah-potter** [comment]
It looks like @grantlemons is looking into this. Grant: I'd suggest creating a new Harper `Parser` that wraps another parser. Have it collapse any token strings that match the pattern `Word` `Underscore` `Word` or `Word` `Hyphen` `Word` AND exist in a provided identifier dictionary. Let me know if you have any questions.

**Comment by elijah-potter** [comment]
We're actually going to reopen this issue until we have a release out that @dvdsk can confirm no longer has the problem.

**Comment by dvdsk** [comment]
Thank you all very much for working on this! Ill go try it out immediately and let you know how it works after the weekend :+1:

**Comment by dvdsk** [comment]
Worked in most cases :tada:. I ran into one issue thats still there but I think it has a different cause. So great work thanks you all very much! I will make a new report for the new issue.

**Comment by dvdsk** [comment]
nvmd it all works perfectly! No other issues on my end :partying_face:

**Comment by dvdsk** [comment]
Apologies if this is spamy. But this feature just really helped my out. I refactored an API and forgot to update the docs. Harper gave me spell errors for words that where identifiers of the previous API. 

Very very nice

**Comment by elijah-potter** [comment]
Not spamy at all. That actually makes us so happy. Glad Harper is doing something good.
