### ISSUE TITLE
Very Minor false positive, rustdoc: plural where singular is a link 

### ISSUE THREAD

**Issue by dvdsk** [elijah-potter/harper#232]
```rust
/// You should create multiple  [`Sink`]s.
```

The goal here is to have the word `Sink` be the link since that is the object that is linked to. This shows up in the rendered docs as the word Sinks where the first 4 letters are blue.

Harper currently treats this as the word `Sink` followed by `s.`

**Comment by elijah-potter** [comment]
This is a duplicate of #187. Please refer to that issue for updates on this.
