### ISSUE TITLE
harper obsidian plug-in offline use?

### ISSUE THREAD

**Issue by somehowko** [elijah-potter/harper#239]
was convinced that Harper obsidian plug in, as other harper plugins would automatically download harper-ls and core, and run it, but it seems not the case.

Maybe I am dead wrong here. Hence the question, is obsidian plugin stand-alone or do I need internet access to use it?

If later is the case, would there be anyway to make it locally available?

P.S, I was reading the contribution page and if there is anyone working on other languages, it seems like there is none. 
Do you happen to know if there is any?

**Comment by elijah-potter** [comment]
The Harper Obsidian plugin has a bundled WebAssembly binary that contains harper-core. I'm hearing that, having installed Harper, you aren't getting any grammar checking, even with it enabled?

**Comment by elijah-potter** [comment]
Since I haven't heard back from you, I'm assuming you're no longer having this problem. Feel free to reopen the issue if needed.
