### ISSUE TITLE
Feature request: `diagnosticSeverity` support

### ISSUE THREAD

**Issue by mawkler** [elijah-potter/harper#36]
Hi! I think it would be great if harper supported a user specified [`diagnosticSeverity`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic) 🙂

**Comment by elijah-potter** [comment]
Sorry it took so long for me to respond to this issue. When you mean user-specified, are you meaning on a per-lint basis or blanket for the whole LSP? 

I really appreciate your using Harper. I want to make it as great of an experience as I can.

**Comment by mawkler** [comment]
No worries! I mean setting one severity level that applies to all diagnostics. I would personally prefer if I could set it so that they all show up as `HINT`s for me 🙂

**Comment by elijah-potter** [comment]
I can make that happen pretty quick. Expect a new release by the end of the day.

**Comment by mawkler** [comment]
Awesome!

**Comment by elijah-potter** [comment]
Alright. It's been implemented in the latest release.

I've set `hint` as default, so no action should be needed for your case.
You can see the config options [here](https://github.com/elijah-potter/harper/tree/master/harper-ls#configuration).

**Comment by mawkler** [comment]
Thank you very much! 😄

**Comment by David-Else** [comment]
https://github.com/elijah-potter/harper/tree/master/harper-ls#configuration now leads to https://writewithharper.com/docs/integrations/language-server and there is no mention of config options for diagnosticSeverity.

**Comment by elijah-potter** [comment]
@David-Else you're absolutely right. I've updated the language server page to direct people to other relevant configuration pages. 

If you use Neovim in particular, [this page is a good place to start.](https://writewithharper.com/docs/integrations/neovim#Configuration)

**Comment by David-Else** [comment]
@elijah-potter I am using Helix and would not have found the info on configuration unless I read this thread and knew to look inside the Neovim section.

I think the language server configuration at https://writewithharper.com/docs/integrations/neovim#Configuration should actually be in the https://writewithharper.com/docs/integrations/language-server section with a note to say it is in Neovim format but can easily be converted to work with other Editors, something like:


> # Configuration

> The configuration options are provided in Neovim format. However, you can convert these settings to work in Helix and Zed as well.


Cheers for the great software!
