### ISSUE TITLE
bug: checking go directives

### ISSUE THREAD

**Issue by lukasmwerner** [elijah-potter/harper#44]
When using Harper on Go codebases it would be nice to ignore checking Go comments that start with `//go:*` as these comments are directives for the compiler. The following is a example:
```go
//go:embed templates/login.html
var LoginPageHTML string
```

The documentation on this Go feature is [here](https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives)

**Comment by elijah-potter** [comment]
This has been implemented as of the latest commit.
