### ISSUE TITLE
bug: parsing error on words containing non English characters 

### ISSUE THREAD

**Issue by henriklovhaug** [elijah-potter/harper#74]
If I try to write a name of something containing non English characters, `harper-ls` tries to spellcheck the substring after the special character. I don't expect it to recognise names from other languages since it's meant for English, but it hinders me from adding the whole word to the global/local dictionary using my editor's quick fix.

Example: 
I try to write the word `Løvetann`. `harper-ls` asks if I ment to spell `vetann` this way, and the quick fix option is to add `vetann` to the dictionary. 

Requested behaviour:
I would like `harper-ls` to mark the whole word, and give me the option to add `Løvetann` to the global/local dictionary.

**Comment by elijah-potter** [comment]
Thank you for bringing this to my attention. I'll try to get a fix available as soon as possible.

**Comment by lukasmwerner** [comment]
Just encountered this as well. Here an example case
```markdown
## Naïve Algorithm
```
harper offers to change the `ve` part of the word.

**Comment by elijah-potter** [comment]
I've included *some* non-English characters into words in the latest Git commits, but not all (not CJK, for example). Hopefully this resolves issues with the kinds of words y'all have mentioned without unnecessarily linting intentionally non-English text.

Let me know if this crops up again (after the next version of `harper-ls` is release and you've updated). For now, I'm going to close the issue.

Thank you for bringing this to my attention.
