### ISSUE TITLE
Useless message from harper-ls on every buffer change

### ISSUE THREAD

**Issue by stepanzak** [elijah-potter/harper#82]
Hi, thanks for this amazing project :)
I have a problem with harper-ls in neovim: every time I change anything in a buffer (e.g. type a character), I get a message from harper-ls with only the text "Linting...". Those messages spam my view when I type. Here's a screenshot:
![Screenshot_from_2024-05-05 21-56-29](https://github.com/elijah-potter/harper/assets/99094176/babedee4-7208-4ae4-9294-6e542e90124e)
Is there a way to disable it?

**Comment by elijah-potter** [comment]
Thanks for pointing this out! This is actually fixed in the most recent commits. I'll look into creating a new release as soon as possible.

**Comment by elijah-potter** [comment]
Alright! The change has been published. It will take a bit for Mason to pick up the new binaries, but it should land soon.
