### ISSUE TITLE
Attempts to replace a comment hyphen with a capital letter when using Lua Code Action.

### ISSUE THREAD

**Issue by The-Briel-Deal** [elijah-potter/harper#87]
Using Neovim v0.9.5, using Mason and Lsp-Zero for LSP installation and Management. Using Arch with latest packages as of this morning.

Hey Harper Contributors and Maintainers, thanks for all the hard work on this project. This issue isn't critical but none the less I thought I would report it (:

Harper LS is giving me a warning about the first letter in a comment in Lua not being capital. This on its own is correct, but when the comment is on a line indented by one or more tabs, it positions the warning one character before it should. This also compounds as you can see below. Because of this when you attempt to use the code action to fix this issue it puts the Capital letter in the wrong spot.

There's a chance this is a Neovim bug so let me know if you have any trouble reproing. My config is also linked below.

![20240518_17h18m59s_grim](https://github.com/elijah-potter/harper/assets/86860060/50ef6667-580b-4253-b281-5cba0535fb1d)

Please let me know if I can provide any more useful info!

For more context on my config see:
https://github.com/The-Briel-Deal/config

![20240518_17h15m41s_grim](https://github.com/elijah-potter/harper/assets/86860060/1c0814c8-8cd6-403e-a06d-347efa2e6af0)
![20240518_17h07m58s_grim](https://github.com/elijah-potter/harper/assets/86860060/acd048ae-4ea1-41fd-9769-5cd5308e526c)
![20240518_17h09m50s_grim](https://github.com/elijah-potter/harper/assets/86860060/21d590c6-da42-4413-a144-49ef4b75108a)
![20240518_17h10m42s_grim](https://github.com/elijah-potter/harper/assets/86860060/f0d4cd31-bb8d-45ce-a5c3-c364126cc541)

**Comment by elijah-potter** [comment]
Thanks for submitting such a detailed issue. I'm sorry it so long for me to get around to this, I've had an admittedly hectic week 😅. I'll look into getting a fix prepared as soon as possible.

**Comment by The-Briel-Deal** [comment]
Oh np! Absolutely no rush (: it doesn't bother me, I just noticed this edge case and figured I'de report it. Thank you for your work on the project!

**Comment by elijah-potter** [comment]
@The-Briel-Deal Just wanted to check in. Mason finally put through `harper-ls` `v0.8.5`. Do you still get this issue on that version?

**Comment by elijah-potter** [comment]
Again, I'm so sorry it took so long for this to get fixed. It will be in the next release.

**Comment by The-Briel-Deal** [comment]
Hey Elijah! From my brief testing things seem to be resolved! And no worries at all about it taking a bit, ultimately this is just something free you are volunteering your time towards so you have no obligation to do this quickly or at all. I (and i'm sure many others) appreciate the effort you put into Harperls though!
