### ISSUE TITLE
feat: Support Email

### ISSUE THREAD

**Issue by lukasmwerner** [elijah-potter/harper#91]
Some email clients embed vim or neovim and it would be super cool to use harper to proof my emails im writing. Neovim recognizes the filetype to be mail. It could essentially be treated as a text file.

**Comment by elijah-potter** [comment]
I can make this happen. Two questions: what email client are you using, and by "text file", do you mean plaintext, or Markdown?

**Comment by lukasmwerner** [comment]
Sweet! I'm using [Aerc](https://aerc-mail.org/) mail which just sub-shells out to neovim plus a file e.g. "/.../aerc-compose-2650687518.eml". By text I mean just plaintext although it could be that users would want to write with markdown in their email.
