### ISSUE TITLE
Duplicate Correction Suggestions

### ISSUE THREAD

**Issue by arthurmayer** [elijah-potter/harper#94]
The word "punctation" (and similar variations, e.g. "punctations" and "punctuations") will produce two suggestions for replacing the word with "punctuation". Produced on the WriteWithHarper website.

![image](https://github.com/elijah-potter/harper/assets/25376540/ed0dcc86-7c4b-4c4e-a411-949cdcc98732)

**Comment by elijah-potter** [comment]
Thanks for pointing this out! You've found a relatively obscure bug, but I've managed to locate and squash it as of the latest commits.
