### ISSUE TITLE
Bug: Ordinal lint confused 

### ISSUE THREAD

**Issue by lukasmwerner** [elijah-potter/harper#95]
In the following document harper belives that "2" in the title should be changing the "the"
```markdown
# 2

The 
```

The lint warning is: `This number needs a different suffix to sound right.` and the suggested fix is: `Replace with: “nd”`

**Comment by elijah-potter** [comment]
I'm unable to replicate this issue on the latest version of Harper. Would you mind confirming that it no longer plagues us so I may close this issue?

**Comment by lukasmwerner** [comment]
I cant replicate it either! Closing.
