### ISSUE TITLE
Add support for "i.e." and "e.g."

### ISSUE THREAD

**Issue by 22ispencer** [elijah-potter/harper#98]
I only started using harper today, and I don't know if this is a reasonable ask or not, but I'm using the LSP in neovim, and it's giving me capitalization warnings for the tokens "i.e." and "e.g.". If there is some setting I could tweak, that'd be great too.

**Comment by elijah-potter** [comment]
Yeah, that's kind of an embarrassing false positive. I'll get a fix pushed and published by EOD.

**Comment by 22ispencer** [comment]
Thanks!

**Comment by elijah-potter** [comment]
It should be published now. I'm seeing some issues on Windows, but other platforms should be just fine. Let me know if you encounter any more issues.
