### ISSUE TITLE
feat: add to nix pkgs

### ISSUE THREAD

**Issue by Feel-ix-343** [elijah-potter/harper#99]

**Comment by elijah-potter** [comment]
I don't have any experience writing Nix packages. Would you be able to pick this up or point me in the right direction?

I don't imagine it would be crazy, since `harper-ls` is just a single binary.

**Comment by Feel-ix-343** [comment]
Seems that a maintainer has picked it up on the nixpkgs repo

**Comment by elijah-potter** [comment]
Sweet. Cool if I close this issue then?
